- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Install ohmyzsh for users with zsh shell
  shell: |
    if [ ! -d "/home/{{ item.name }}/.oh-my-zsh" ]; then
      git clone https://github.com/ohmyzsh/ohmyzsh.git /home/{{ item.name }}/.oh-my-zsh
      cp /home/{{ item.name }}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{ item.name }}/.zshrc
      chown -R {{ item.name }}:{{ item.name }} /home/{{ item.name }}/.oh-my-zsh
      chown {{ item.name }}:{{ item.name }} /home/{{ item.name }}/.zshrc
    fi
  loop: "{{ users }}"
  when: item.shell == '/bin/zsh'
