- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Create images directory
  file:
    path: /var/www/images
    state: directory
    mode: '0755'

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
